---
title: "Shera Adams"
email: "shera.adams@snhu.edu"
description: "Coursework for Southern New Hampshire University in Computer Science "
theme: "jekyll-theme-architect"
logo: "/assets/img/profile.jpg"
---
